[package]
name = "backend"
version = "1.0.0"
authors = ["Julien Blatecky <julien.blatecky@creatiwity.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.5"
custom_error = "1.8"
diesel = { version = "1.4", features = ["postgres", "chrono", "r2d2", "serde_json", "uuidv07"] }
diesel_migrations = { version = "1.4", features = ["postgres"] }
dotenv = "0.15"
log = "0.4"
pretty_env_logger = "0.4"
r2d2 = "0.8"
rand = "0.7"
rust-crypto = "0.2"
rust-embed = "5.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
validator = "0.11"
validator_derive = "0.12"
warp = "0.2"

[dependencies.lettre]
git = "https://github.com/julien1619/lettre"
default-features = false
features = ["builder", "smtp-transport", "rustls-tls", "r2d2", "hostname", "serde"]

[target.'cfg(any(unix, linux))'.dependencies]
openssl = "0.10"
