name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build for MUSL
        run: |
          mkdir -p ~/.cargo/{git,registry}
          docker pull clux/muslrust:stable
          docker run \
            -v ~/.cargo/registry:/root/.cargo/registry \
            -v ~/.cargo/git:/root/.cargo/git \
            -v $GITHUB_WORKSPACE:/volume \
            --user $(id -u):$(id -g) \
            --rm -t clux/muslrust:stable \
            sh -c "/volume/build-musl.sh && chown -R $(id -u):$(id -g) ./target /root/.cargo/registry /root/.cargo/git"
      - name: Archive production artifact
        uses: actions/upload-artifact@v2
        with:
          name: covid-journal-backend
          path: dist/backend
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF##*/}
      - name: Docker build
        env:
          IMAGE_NAME: covid-journal-backend
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          docker build --tag $IMAGE_NAME:$VERSION "./dist"
      - name: Docker publish
        env:
          IMAGE_NAME: covid-journal-backend
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
          docker tag $IMAGE_NAME:$VERSION docker.pkg.github.com/covidjournal/backend/$IMAGE_NAME:$VERSION
          docker push docker.pkg.github.com/covidjournal/backend/$IMAGE_NAME:$VERSION
